# SPDX-License-Identifier: GPL-3.0-or-later
from tests.wallbox_update_cycle_controller_cases_primary import TestUpdateCycleControllerPrimary
from tests.wallbox_update_cycle_controller_cases_secondary import TestUpdateCycleControllerSecondary
from tests.wallbox_update_cycle_controller_cases_tertiary import TestUpdateCycleControllerTertiary
from tests.wallbox_update_cycle_controller_cases_quaternary import TestUpdateCycleControllerQuaternary
from tests.wallbox_update_cycle_controller_cases_quinary import TestUpdateCycleControllerQuinary
from tests.wallbox_update_cycle_controller_cases_senary import TestUpdateCycleControllerSenary
from tests.wallbox_update_cycle_controller_cases_septenary import TestUpdateCycleControllerSeptenary
from tests.wallbox_update_cycle_controller_cases_octonary import TestUpdateCycleControllerOctonary
from tests.wallbox_update_cycle_controller_cases_nonary import TestUpdateCycleControllerNonary
from tests.wallbox_update_cycle_controller_cases_denary import TestUpdateCycleControllerDenary
from tests.wallbox_update_cycle_controller_cases_undenary import TestUpdateCycleControllerUndenary
from tests.wallbox_update_cycle_controller_cases_duodenary import TestUpdateCycleControllerDuodenary
from tests.wallbox_update_cycle_controller_cases_trecenary import TestUpdateCycleControllerTrecenary
from tests.wallbox_update_cycle_controller_cases_quattuordenary import TestUpdateCycleControllerQuattuordenary
from tests.wallbox_update_cycle_controller_cases_quindenary import TestUpdateCycleControllerQuindenary

__all__ = [
    "TestUpdateCycleControllerPrimary",
    "TestUpdateCycleControllerSecondary",
    "TestUpdateCycleControllerTertiary",
    "TestUpdateCycleControllerQuaternary",
    "TestUpdateCycleControllerQuinary",
    "TestUpdateCycleControllerSenary",
    "TestUpdateCycleControllerSeptenary",
    "TestUpdateCycleControllerOctonary",
    "TestUpdateCycleControllerNonary",
    "TestUpdateCycleControllerDenary",
    "TestUpdateCycleControllerUndenary",
    "TestUpdateCycleControllerDuodenary",
    "TestUpdateCycleControllerTrecenary",
    "TestUpdateCycleControllerQuattuordenary",
    "TestUpdateCycleControllerQuindenary",
]
