# SPDX-License-Identifier: GPL-3.0-or-later
from tests.test_venus_evcharger_state_contracts_support import *  # noqa: F401,F403
from tests.test_venus_evcharger_state_contracts_part1 import _TestVenusEvchargerStateContractsPart1
from tests.test_venus_evcharger_state_contracts_part2 import _TestVenusEvchargerStateContractsPart2
from tests.test_venus_evcharger_state_contracts_part3 import _TestVenusEvchargerStateContractsPart3

class TestVenusEvchargerStateContracts(_TestVenusEvchargerStateContractsPart1, _TestVenusEvchargerStateContractsPart2, _TestVenusEvchargerStateContractsPart3, unittest.TestCase):
    pass
