# SPDX-License-Identifier: GPL-3.0-or-later
from tests.venus_evcharger_shelly_io_controller_cases_quaternary_support import *  # noqa: F401,F403
from tests.venus_evcharger_shelly_io_controller_cases_quaternary_part1 import _TestShellyIoControllerQuaternaryPart1
from tests.venus_evcharger_shelly_io_controller_cases_quaternary_part2 import _TestShellyIoControllerQuaternaryPart2

class TestShellyIoControllerQuaternary(_TestShellyIoControllerQuaternaryPart1, _TestShellyIoControllerQuaternaryPart2, ShellyIoControllerTestBase):
    pass
