# SPDX-License-Identifier: GPL-3.0-or-later
from tests.venus_evcharger_backend_factory_primary_cases_support import *  # noqa: F401,F403
from tests.venus_evcharger_backend_factory_primary_cases_part1 import _TestShellyWallboxBackendFactoryPrimaryPart1
from tests.venus_evcharger_backend_factory_primary_cases_part2 import _TestShellyWallboxBackendFactoryPrimaryPart2

class TestShellyWallboxBackendFactoryPrimary(_TestShellyWallboxBackendFactoryPrimaryPart1, _TestShellyWallboxBackendFactoryPrimaryPart2, unittest.TestCase):
    pass
