# SPDX-License-Identifier: GPL-3.0-or-later
from tests.venus_evcharger_bootstrap_controller_runtime_cases_support import *  # noqa: F401,F403
from tests.venus_evcharger_bootstrap_controller_runtime_cases_part1 import _TestServiceBootstrapControllerRuntimePart1
from tests.venus_evcharger_bootstrap_controller_runtime_cases_part2 import _TestServiceBootstrapControllerRuntimePart2

class TestServiceBootstrapControllerRuntime(_TestServiceBootstrapControllerRuntimePart1, _TestServiceBootstrapControllerRuntimePart2, ServiceBootstrapControllerTestCase):
    pass
