# SPDX-License-Identifier: GPL-3.0-or-later
from tests.venus_evcharger_publisher_diagnostic_cases_support import *  # noqa: F401,F403
from tests.venus_evcharger_publisher_diagnostic_cases_part1 import _TestDbusPublishControllerDiagnosticsPart1
from tests.venus_evcharger_publisher_diagnostic_cases_part2 import _TestDbusPublishControllerDiagnosticsPart2

class TestDbusPublishControllerDiagnostics(_TestDbusPublishControllerDiagnosticsPart1, _TestDbusPublishControllerDiagnosticsPart2, DbusPublishControllerTestCase):
    pass
