# SPDX-License-Identifier: GPL-3.0-or-later
"""Shared lightweight contracts for normalized wallbox state and snapshots."""

from __future__ import annotations

from shelly_wallbox.core.contracts_basic import (
    AUTO_STATE_CODES,
    LEARNED_CHARGE_POWER_PHASES,
    LEARNED_CHARGE_POWER_STATES,
    finite_float_or_none,
    non_negative_float_or_none,
    non_negative_int,
    normalize_auto_state,
    normalize_binary_flag,
    normalize_learning_phase,
    normalize_learning_state,
    normalize_optional_binary_state,
    normalized_auto_state_pair,
    normalized_fault_state,
    normalized_status_source,
    paired_optional_values,
    thresholds_ordered,
    timestamp_age_within,
    timestamp_not_future,
    valid_battery_soc,
)
from shelly_wallbox.core.contracts_bootstrap import (
    BOOTSTRAP_UPDATE_MODES,
    BOOTSTRAP_UPDATE_RESULTS,
    normalized_bootstrap_string_list,
    normalized_bootstrap_update_mode,
    normalized_bootstrap_update_result,
    normalized_bootstrap_update_status_fields,
)
from shelly_wallbox.core.contracts_outward import (
    AUTO_METRIC_NUMERIC_FIELDS,
    AUTO_METRIC_TEXT_FIELDS,
    SCHEDULED_REASON_CODES,
    SCHEDULED_STATE_CODES,
    SOFTWARE_UPDATE_STATE_CODES,
    displayable_confirmed_read_timestamp,
    normalized_scheduled_state_fields,
    normalized_software_update_state_fields,
    sanitized_auto_metrics,
)
from shelly_wallbox.core.contracts_snapshot import (
    _resolved_snapshot_captured_at,
    cutover_confirmed_off,
    normalized_auto_decision_trace,
    normalized_worker_snapshot,
    write_failure_is_reversible,
)


__all__ = [
    "AUTO_METRIC_NUMERIC_FIELDS",
    "AUTO_METRIC_TEXT_FIELDS",
    "AUTO_STATE_CODES",
    "BOOTSTRAP_UPDATE_MODES",
    "BOOTSTRAP_UPDATE_RESULTS",
    "LEARNED_CHARGE_POWER_PHASES",
    "LEARNED_CHARGE_POWER_STATES",
    "SCHEDULED_REASON_CODES",
    "SCHEDULED_STATE_CODES",
    "SOFTWARE_UPDATE_STATE_CODES",
    "_resolved_snapshot_captured_at",
    "cutover_confirmed_off",
    "displayable_confirmed_read_timestamp",
    "finite_float_or_none",
    "non_negative_float_or_none",
    "non_negative_int",
    "normalize_auto_state",
    "normalize_binary_flag",
    "normalized_bootstrap_string_list",
    "normalized_bootstrap_update_mode",
    "normalized_bootstrap_update_result",
    "normalized_bootstrap_update_status_fields",
    "normalize_learning_phase",
    "normalize_learning_state",
    "normalize_optional_binary_state",
    "normalized_auto_decision_trace",
    "normalized_auto_state_pair",
    "normalized_fault_state",
    "normalized_scheduled_state_fields",
    "normalized_software_update_state_fields",
    "normalized_status_source",
    "normalized_worker_snapshot",
    "paired_optional_values",
    "sanitized_auto_metrics",
    "thresholds_ordered",
    "timestamp_age_within",
    "timestamp_not_future",
    "valid_battery_soc",
    "write_failure_is_reversible",
]
